### ISSUE TITLE
BTAD的结果

### ISSUE THREAD

**Issue by FourthM** [xcyao00/PMAD#2]
你好，想问一下您，您的论文中提到在BTAD数据集也做了实验，但是没有找到您的附录文件，如果您方便的话，可以提供一下这个数据集上的结果吗，非常感谢！

**Comment by xcyao00** [comment]
We train on one product and apply on other two products. The detailed results are:

 train: product1
 product2 0.858/0.956
 product3 1.000/0.996
 mean        0.929/0.976

train: product2
product1  0.978/0.964
product3  1.000/0.996
mean        0.989/0.980

train: product3
product1   0.977/0.964
product2  0.820/0.957
mean        0.898/0.960

**Comment by FourthM** [comment]
Thank you very much for your reply! Best Regards!
